export const SEARCH_BOOKS_START = 'SEARCH_BOOKS_START';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAIL = 'SEARCH_BOOKS_FAIL';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';
export const FETCH_BOOKS = 'FETCH_BOOKS';

export const SAVE_BOOKS_START = 'SAVE_BOOKS_START';
export const SAVE_BOOKS_SUCCESS = 'SAVE_BOOKS_SUCCESS';
export const SAVE_BOOKS_FAIL = 'SAVE_BOOKS_FAIL';
export const SAVE_BOOKS = 'SAVE_BOOKS';

export const REMOVE_BOOKS_START = 'REMOVE_BOOKS_START';
export const REMOVE_BOOKS_SUCCESS = 'REMOVE_BOOKS_SUCCESS';
export const REMOVE_BOOKS_FAIL = 'REMOVE_BOOKS_FAIL';
export const REMOVE_BOOKS = 'REMOVE_BOOKS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const LOGOUT_MESSAGE = 'LOGOUT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
