export const SEARCH_BOOKS_START = 'SEARCH_BOOKS_START';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAIL = 'SEARCH_BOOKS_FAIL';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';
